URL ?= https://docs.google.com/spreadsheets/d/18fXVSZg_z7wNsGm0SaLHHftdI7MB_r59NnAGZ-VxY-s/edit

00:
	manytables pull --type spreadsheet --url=${URL}

01:
	manytables show manytables

02:
	manytables push manytables

03:
	manytables push --type spreadsheet --name=manytables2 manytables

# 10:
# 	manytables push --type spreadsheet --name=persontables persontables
