URL ?= https://docs.google.com/spreadsheets/d/18fXVSZg_z7wNsGm0SaLHHftdI7MB_r59NnAGZ-VxY-s/edit

00:
	manytables clone --type spreadsheet --url=${URL}

01:
	manytables show manytables

02:
	manytables push --type spreadsheet --name=manytable2 --url=https://docs.google.com/spreadsheets/d/1snkVUG7XyFtZ-CSXNoFDJuHtaTMTBgfX_BxqvqpaG0o/edit manytables
